# Generated by Django 4.1.3 on 2022-12-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('author', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Author Username')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp of the moment the blog was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp of last time blog was updated.')),
            ],
        ),
    ]
